(specifications->manifest
 '(
   ;; Fonts
   "font-mononoki"
   "font-fira-mono"
   "font-fira-code"
   "font-abattis-cantarell"
   "font-dejavu"
   "font-iosevka"
   "font-adobe-source-code-pro"
   ;; "font-google-noto" ; large file (~700 mb)
   "font-google-roboto"
   "font-gnu-freefont"
   "font-liberation"
   "font-awesome"
   "font-google-material-design-icons"
   "gs-fonts"
   
   "fontmanager"
   "fontconfig""qutebrowser""mpv"
   "mpv-mpris"
   "youtube-dl"
   "mpd"
   "mpdris2"
   "ncmpcpp"
   "playerctl""gstreamer"
   "gst-plugins-base"
   "gst-plugins-good"
   "gst-plugins-bad"
   "gst-plugins-ugly"
   "gst-libav"
   "intel-vaapi-driver"
   "libva-utils"  "feh"
   "imv"
   "gimp"
   "scrot""picom"
   "light"
   "brightnessctl"
   "nitrogen"
   "polybar"
   "pavucontrol"
   "pasystray"
   "volumeicon"
   "blueman"
   ;; "compton"
   "redshift-wayland"
   ;; "gucharmap"
   "fontmanager"
   "xdg-utils"      ;; For xdg-open, etc
   "xdg-dbus-proxy" ;; For Flatpak
   "gtk+:bin"       ;; For gtk-launch
   "glib:bin"       ;; For gio-launch-desktop
   "shared-mime-info"
   "rofi"
   "wofi"
   "waybar"
   "swayidle"
   "swaylock"
   "wl-clipboard"
   "mako"
   "flameshot"
   "evince"
   "deluge"
   "libreoffice"
   "telegram-desktop"
   "qalculate-gtk"
   "pcmanfm"
   "foot"
   "slock"
   "i3lock"
   ;; xmonad stuff
   "xmonad"
   "xmobar"
   "ghc-xmonad-contrib"
   "ghc@8.6.5"
   "ghc-hostname"
   "stalonetray"
   "dunst""btrfs-progs"
   "htop"
   "curl"
   "wget"
   "openssh"
   "zip"
   "unzip"
   "stow""xev"
   "xprop"
   "xdotool"
   "xset"
   "xsetroot"
   "xrdb"
   "xhost"
   "xmodmap"
   "setxkbmap"
   "xrandr"
   "arandr"
   "xss-lock"
   "libinput"
   "xinput"
   "xscreensaver""fish"
   "python"
   "ncurses"
))
